import type { InventoryData } from './types';

// Step 2 uses in-memory mock data so we can build the UI before wiring the backend.
export const mockInventory: InventoryData = {
  folders: [
    { id: 'root', name: 'All inventory', parentId: null },

    { id: 'f-lab', name: 'Lab', parentId: 'root' },
    { id: 'f-optics', name: 'Optics', parentId: 'f-lab' },
    { id: 'f-electronics', name: 'Electronics', parentId: 'f-lab' },

    { id: 'f-field', name: 'Field kits', parentId: 'root' },
    { id: 'f-arctic', name: 'Arctic', parentId: 'f-field' },
    { id: 'f-alps', name: 'Alps', parentId: 'f-field' },

    { id: 'f-office', name: 'Office', parentId: 'root' },
  ],
  items: [
    {
      id: 'i-oc-1',
      folderId: 'f-optics',
      name: 'OCARINA – alignment target',
      sku: 'OC-ALIGN-001',
      quantity: 3,
      unit: 'pcs',
      tags: ['optics', 'calibration'],
      location: 'Drawer A3',
      updatedAtIso: '2025-12-20T10:15:00.000Z',
      imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=60',
    },
    {
      id: 'i-oc-2',
      folderId: 'f-optics',
      name: 'Laser safety goggles',
      sku: 'SAFE-LASER-02',
      quantity: 8,
      unit: 'pcs',
      tags: ['safety'],
      location: 'Shelf 2',
      updatedAtIso: '2025-12-18T09:02:00.000Z',
      imageUrl: 'https://images.unsplash.com/photo-1589927986089-35812388d1d2?auto=format&fit=crop&w=800&q=60',
    },
    {
      id: 'i-el-1',
      folderId: 'f-electronics',
      name: 'Arduino R4 WiFi',
      sku: 'ARD-R4-WIFI',
      quantity: 2,
      unit: 'pcs',
      tags: ['electronics', 'prototype'],
      location: 'Box E1',
      updatedAtIso: '2025-12-26T12:40:00.000Z',
      imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&q=60',
    },
    {
      id: 'i-el-2',
      folderId: 'f-electronics',
      name: 'BNC cables (1 m)',
      sku: 'BNC-1M',
      quantity: 14,
      unit: 'pcs',
      tags: ['electronics'],
      location: 'Cabinet 4',
      updatedAtIso: '2025-12-22T15:28:00.000Z',
          attachments: [],
      customFields: [],
    },
    {
      id: 'i-field-1',
      folderId: 'f-arctic',
      name: 'Portable weather station',
      sku: 'WX-PORT-01',
      quantity: 1,
      unit: 'kit',
      tags: ['field', 'meteo'],
      location: 'Case #2',
      updatedAtIso: '2025-12-10T08:10:00.000Z',
      imageUrl: 'https://images.unsplash.com/photo-1501706362039-c6e80948a1c8?auto=format&fit=crop&w=800&q=60',
    },
    {
      id: 'i-field-2',
      folderId: 'f-alps',
      name: 'Crampons',
      sku: 'ALP-CRAMP-01',
      quantity: 4,
      unit: 'pairs',
      tags: ['field', 'safety'],
      location: 'Storage room',
      updatedAtIso: '2025-11-30T18:20:00.000Z',
      imageUrl: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?auto=format&fit=crop&w=800&q=60',
    },
    {
      id: 'i-office-1',
      folderId: 'f-office',
      name: 'Label printer tape (black)',
      sku: 'LBL-TAPE-BK',
      quantity: 6,
      unit: 'rolls',
      tags: ['office'],
      location: 'Supply closet',
      updatedAtIso: '2025-12-05T11:05:00.000Z',
          attachments: [],
      customFields: [],
    },
  ],
};
